name: Deploy to DigitalOcean

on:
  workflow_dispatch:
  push:
    branches:
      - main
  repository_dispatch:
    types: [trigger-deploy]

permissions:
  issues: write
  pull-requests: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SERVER_IP: 192.34.62.11

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Extract Python version from Pipfile
      id: python_version
      run: |
        PYTHON_VERSION=$(grep "python_version" Pipfile | cut -d '"' -f2)
        echo "python-version=$PYTHON_VERSION" >> $GITHUB_ENV


    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Build database
      run: |
        pipenv install
        pipenv run python main.py

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

      env:
        SSH_PRIVATE_KEY: ${{ secrets.id_ed25519_TorontoLobbyistRegistryPublic }}

    - name: Sync files using rsync
      run: |
        rsync -avz --delete \
        ./ root@$SERVER_IP:/root/TorontoLobbyistRegistry

    - name: Restart the application
      run: ssh root@$SERVER_IP "systemctl restart TorontoLobbyistRegistry"