name: Deploy to Vercel

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install

    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |
        if [ "${{ github.ref }}" = "refs/heads/main" ]; then
          pipenv run ./deploy.sh
        else
          pipenv run ./deploy.sh --no-prod
        fi