name: Minimal Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run a one-line script
      run: echo Hello, world!