name: Download, Unzip and Save Lobbyist Registry Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  download_lobby_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout TorontoLobbyistRegistryData
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TORONTOLOBBYISTREGISTRY_SCRAPE }}
          path: TorontoLobbyistRegistryData
          ref: 'test'
      - name: Echo commit hash of TorontoLobbyistRegistry
        run: |
          TorontoLobbyistRegistry_commit_hash=$(git rev-parse HEAD)
          echo "TorontoLobbyistRegistry_commit_hash=${TorontoLobbyistRegistry_commit_hash}" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install pipenv
        run: |
          pip install --upgrade pip
          pip install pipenv
      - name: Install dependencies with pipenv
        run: |
          pipenv install
      - name: Run Python script to download and unzip files
        run: |
          pipenv run python download_and_extract.py 
          cd TorontoLobbyistRegistryData
          mv ../lobbyactivity-active.xml lobbyactivity-active.xml
          mv ../lobbyactivity-closed.xml lobbyactivity-closed.xml
          mv ../lobbyist-registry-readme.xls lobbyist-registry-readme.xls
          mv ../open-data-response.json open-data-response.json
          mv ../"Lobbyist Registry Activity.zip" "Lobbyist Registry Activity.zip"
      - name: Commit and push if files changed
        run: |-
          cd TorontoLobbyistRegistryData
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add lobbyactivity-active.xml
          git add lobbyactivity-closed.xml
          git add lobbyist-registry-readme.xls
          git add open-data-response.json
          git add "Lobbyist Registry Activity.zip"
          timestamp=$(date -u)
          git commit -m "Dowloaded: ${timestamp}: commit: ${{env.TorontoLobbyistRegistry_commit_hash}}" || exit 0
          git push origin test
