name: Download, Unzip and Save Lobbyist Registry Data

on:
  workflow_dispatch:
  schedule:
    - cron: '30 21 * * *'
jobs:
  download_lobby_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Echo commit hash of TorontoLobbyistRegistry
        run: |
          TorontoLobbyistRegistry_commit_hash=$(git rev-parse HEAD)
          echo "TorontoLobbyistRegistry_commit_hash=${TorontoLobbyistRegistry_commit_hash}" >> $GITHUB_ENV
          echo "TorontoLobbyistRegistry_commit_hash=${TorontoLobbyistRegistry_commit_hash}"
      - name: Checkout TorontoLobbyistRegistryData
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TORONTOLOBBYISTREGISTRY_SCRAPE }}
          repository: 'RamVasuthevan/TorontoLobbyistRegistryData'
          path: TorontoLobbyistRegistryData
          ref: 'main'
      - name: Checkout TorontoLobbyistRegistryReportsData
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TORONTOLOBBYISTREGISTRY_SCRAPE }}
          repository: 'RamVasuthevan/TorontoLobbyistRegistryReportsData'
          path: TorontoLobbyistRegistryReportsData
          ref: 'main'
      - name: Set up Python 3.11.5
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.5'
      - name: Install pipenv
        run: |
          pip install --upgrade pip
          pip install pipenv
      - name: Install dependencies with pipenv
        run: |
          pipenv install
      - name: Run Python script to download and unzip files
        run: |
          cd TorontoLobbyistRegistryData
          pipenv run python ../scripts/download_data.py
      - name: Commit and push if files changed
        run: |-
          cd TorontoLobbyistRegistryData
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add .
          timestamp=$(date -u)
          git commit -m "Downloaded: ${timestamp}: commit: ${{env.TorontoLobbyistRegistry_commit_hash}}" || exit 0
          git push origin main
          - name: Move files to TorontoLobbyistRegistryData
          run: |-
            mv lobbyactivity-active.xml lobbyactivity-closed.xml open-data-response ../TorontoLobbyistRegistryData/
      - name: Run extract_data_to_report_files.py script
        run: |-
          cd TorontoLobbyistRegistryReportsData
          pipenv run python ../scripts/extract_data_to_report_files.py
      - name: Commit and push if files changed in TorontoLobbyistRegistryReportsData
        run: |-
          cd TorontoLobbyistRegistryReportsData
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add .
          timestamp=$(date -u)
          git commit -m "Extracted Reports: ${timestamp}: commit: ${{ env.TorontoLobbyistRegistry_commit_hash }}" || exit 0
          git push origin main
        